// Index.md management
// Purpose: Manage index.md file with video entries

const path = require('path');
const { fileExists, readFile, appendFile, writeFile } = require('../utils/file');
const { truncateText, extractVideoId } = require('../utils/string');

/**
 * Get path to index.md in output directory
 * @param {string} outputDir - Output directory path
 * @returns {string} Full path to index.md
 */
function getIndexPath(outputDir) {
  return path.join(outputDir, 'index.md');
}

/**
 * Check if index.md exists
 * @param {string} outputDir - Output directory path
 * @returns {boolean} True if exists
 */
function indexExists(outputDir) {
  return fileExists(getIndexPath(outputDir));
}

/**
 * Create new index.md with header
 * @param {string} outputDir - Output directory path
 */
function createIndex(outputDir) {
  const indexPath = getIndexPath(outputDir);
  const header = `# Video Transcript Index

Generated by YT Transcript Extractor  
Last updated: ${new Date().toLocaleString()}

---

`;
  
  writeFile(indexPath, header, false);
  console.log(`📝 Created index.md at ${indexPath}`);
}

/**
 * Check if entry already exists in index
 * @param {string} indexPath - Path to index.md
 * @param {string} videoId - YouTube video ID
 * @param {string} filename - Markdown filename
 * @returns {boolean} True if entry exists
 */
function entryExists(indexPath, videoId, filename) {
  const content = readFile(indexPath);
  if (!content) return false;
  
  // Check for video ID or filename in content
  return content.includes(videoId) || content.includes(`(${filename})`);
}

/**
 * Update "Last updated" timestamp in index
 * @param {string} indexPath - Path to index.md
 */
function updateTimestamp(indexPath) {
  let content = readFile(indexPath);
  if (!content) return;
  
  // Replace timestamp line
  const timestampRegex = /Last updated: .*/;
  content = content.replace(timestampRegex, `Last updated: ${new Date().toLocaleString()}`);
  
  writeFile(indexPath, content, false);
}

/**
 * Generate formatted entry for index.md
 * @param {Object} entry - Entry data
 * @returns {string} Formatted entry
 */
function formatIndexEntry(entry) {
  const { title, filename, summary, url, date } = entry;
  // Format: - [[FolderName]] (Date) - Summary. [YouTube](url)
  return `- [[${filename}]] (${date}) - ${summary} [YouTube](${url})\n`;
}

/**
 * Append entry to index.md
 * @param {string} outputDir - Output directory path
 * @param {Object} videoInfo - Video info object
 * @param {string} filename - Markdown filename (without path)
 * @param {string} summary - Video summary
 * @param {string} targetUrl - YouTube URL
 */
function appendIndexEntry(outputDir, videoInfo, filename, summary, targetUrl) {
  const indexPath = getIndexPath(outputDir);
  
  // Create index if it doesn't exist
  if (!indexExists(outputDir)) {
    createIndex(outputDir);
  }
  
  // Extract video ID for duplicate check
  const videoId = videoInfo.videoId || videoInfo.videoInfo?.videoId || extractVideoId(targetUrl);
  
  // Check if entry already exists
  if (entryExists(indexPath, videoId, filename)) {
    console.log(`📋 Entry already exists in index.md, skipping`);
    return;
  }
  
  // Prepare entry data
  const title = videoInfo.title || videoInfo.videoInfo?.title || 'Untitled Video';
  const date = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
  
  // Use provided summary or fallback to description
  let summaryText = summary;
  if (!summaryText) {
    const description = videoInfo.description || videoInfo.videoInfo?.description;
    summaryText = description ? truncateText(description, 150) : 'No summary available.';
  } else {
    summaryText = truncateText(summaryText, 150);
  }
  
  const entry = {
    title,
    filename,
    summary: summaryText,
    url: targetUrl,
    date,
  };
  
  // Append entry
  const formattedEntry = formatIndexEntry(entry);
  appendFile(indexPath, formattedEntry);
  
  // Update timestamp
  updateTimestamp(indexPath);
  
  console.log(`📋 Added entry to index.md: ${title}`);
}

module.exports = {
  getIndexPath,
  indexExists,
  createIndex,
  appendIndexEntry,
};
