# nginx-manager: managed config
# app-name: basic-app
# port: 3000
# path: /basic-app
# auth: none
# websocket: false
# exact: false
# created-at: 2026-02-22T10:00:00.000Z
# domain: rnd.blr0.geekydev.com

location /basic-app {
    proxy_pass http://localhost:3000;
    include /etc/nginx/snippets/proxy-params.conf;
}
